const translations = {
  'en': {
    //COMMON
    'name': 'Name',
    'firstName': 'First Name',
    'lastName': 'Last Name',
    'id': 'ID',
    'password': 'password',
    'password_repeat': 'Password Repeat',
    'user': 'User',
    'client': 'Client',
    'username': 'Username',
    'email': 'Email',
    'action': 'Action',
    'date': 'Date',
    'delivery_date': 'Delivery Date',
    'return': 'Return',
    'returned': 'Returned',
    'return_status': 'Return Status',
    'rental': 'Rental',
    'rentals': 'Rentals',
    'yes': 'Yes',
    'no': 'No',
    'back': 'Back',
    'equipment': 'Equipment',
    'equipments': 'Equipments',
    'quantity': 'Quantity',
    'fee': 'Fee',
    'family': 'Family',
    'families': 'Families',
    'new': 'New',
    'submit': 'Submit',
    'add': 'Add',
    'my': 'My',
    'search': 'Search',
    'active': 'Status',
    //CLIENTS
    'clients_title': 'Clients',
    'clients_total_rentals': 'Total Rentals',
    //Users,
    'list_users': 'List of users',
    //RENTALS
    'add_equipment': 'Add a new equipment',
    'sub_total': 'Sub Total',
    //Equipments
    'equipments': 'Equipments',
    'equipmentsLists': 'Lists of equipments',
    'equipmentsAdd': 'Add new equipment',
    'equipmentsNameValidation': 'Please, input your name',
    'equipmentsFeeValidation': 'Please, input your fee',
    'equipmentNameLabel': 'Name of equipment',
    'equipmentFeeLabel': 'Fee of equipment',
    //STATS
    'statistics': 'Statistics',
    'date_range': 'Date Range',
    'select_data': 'Select Data',
    'select_client': 'Select a client',
    'not_returned_rentals': 'Not Returned Rentals',
    'average_days_rentals': 'Average of days rentals',
    'history_rentals': 'History rentals of clients',
    'historial': 'Historial',
    //Register
    'register_back': 'Are you registred?',
    'register_submit': 'Register',
    'sign_up': 'Sign up',
    //Login
    'login': 'Login',
    'username_email': 'Username or e-mail',
    'login_submit': 'Login',
    'login_register': 'Register',
    //Menu
    'dashboard': 'Dashboard',
    'clients': 'Clients',
    'users': 'Users',
    //Me
    'me': 'My profile',
  },
  'es': {
    //COMMON
    'editUser': 'Editar Usuario',
    'name': 'Nombre',
    'firstName': 'Primer Nombre',
    'lastName': 'Segundo Nombre',
    'id': 'Cédula',
    'password': 'Contraseña',
    'password_repeat': 'Repite la contraseña',
    'user': 'Usuario',
    'client': 'Cliente',
    'username': 'Usuario',
    'email': 'Correo',
    'action': 'Acción',
    'date': 'Fecha',
    'delivery_date': 'Fecha de Entrega',
    'return': 'Retorno',
    'returned': 'Retornado',
    'return_status': 'Estado de Retorno',
    'rental': 'Renta',
    'rentals': 'Rentas',
    'yes': 'Sí',
    'no': 'No',
    'back': 'Volver',
    'equipment': 'Equipo',
    'equipments': 'Equipos',
    'quantity': 'Cantidad',
    'fee': 'Tarifa',
    'family': 'Familia',
    'families': 'Familias',
    'new': 'Nuevo',
    'submit': 'Enviar',
    'add': 'Agregar',
    'my': 'Mis',
    'search': 'Buscar',
    'active': 'Estado',
    //CLIENTS
    'clients_title': 'Clientes',
    'clients_total_rentals': 'Total de Rentas',
    //Users,
    'list_users': 'Lista de usuarios',
    //RENTALS
    'add_equipment': 'Agregar un nuevo equipo',
    'sub_total': 'Sub Total',
    //Equipments
    'equipments': 'Equipos',
    'equipmentsLists': 'Listado de equipos',
    'equipmentsAdd': 'Agregar nuevo equipo',
    'equipmentsNameValidation': 'Por favor, introduzca el nombre.',
    'equipmentsFeeValidation': 'Por favor, introduzca la tarifa',
    'equipmentNameLabel': 'Nombre del equipo',
    'equipmentFeeLabel': 'Tarifa del equipo',
    //STATS
    'statistics': 'Estadisticas',
    'date_range': 'Rango de fecha',
    'select_data': 'Seleccione Datos',
    'select_client': 'Seleccione un cliente',
    'not_returned_rentals': 'Rentas sin retornar',
    'average_days_rentals': 'Promedio rentados',
    'history_rentals': 'Historial de rentas',
    'historial': 'Historial',
    //Register
    'register_back': '¿Estás registrado?',
    'register_submit': 'Registrar',
    'sign_up': 'Registrar usuario',
    //Login
    'login': 'Iniciar Sesión',
    'username_email': 'Usuario o e-mail',
    'login_submit': 'Iniciar Sesión',
    'login_register': 'Registrar',
    //Menu
    'dashboard': 'Panel',
    'clients': 'Clientes',
    'users': 'Usuarios',
    'me': 'Mi perfil'
  }
}

export const getTranslated = (data) => {
  return translations[data.lang.substring(0, 2)];
}
