spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:SpringBoot
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  jackson:
    default-property-inclusion: non_null

  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
  security:
    user:
      name: admin
      password: admin
      roles: USER, ADMIN
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration